"""内容分析阶段一的纯领域内核。"""

from .analyzer import ContentAnalyzer, ProjectAssessment, enforce_analysis_boundaries
from .deterministic import (
    deduplicate_contents,
    derive_windows,
    normalize_play_count,
    persona_like_baseline,
    qianchuan_top_three,
)
from .engine import (
    AccountSyncResult,
    ContentAnalysisEngine,
    CrossProjectCandidate,
    EngineResult,
    InteractionOverview,
    LibraryCandidate,
    MetricSummary,
    OfflineRunInput,
    ProjectDailyReport,
    ReportItem,
    SavedBusinessState,
    SavedLibraryRecord,
)
from .domain import (
    AnalysisWindows,
    BasicAnalysis,
    DataMaturity,
    ContentCategory,
    ContentIdentity,
    ContentRecord,
    ContentSource,
    EngagementMetrics,
    InteractionObservation,
    InteractionObservationType,
    InteractionMetric,
    LikeBaseline,
    OpeningKind,
    RelativePerformanceLevel,
)

__all__ = [
    "AnalysisWindows",
    "AccountSyncResult",
    "BasicAnalysis",
    "DataMaturity",
    "ContentAnalysisEngine",
    "ContentAnalyzer",
    "ContentCategory",
    "ContentIdentity",
    "ContentRecord",
    "ContentSource",
    "EngagementMetrics",
    "InteractionObservation",
    "InteractionObservationType",
    "InteractionMetric",
    "LikeBaseline",
    "OpeningKind",
    "RelativePerformanceLevel",
    "CrossProjectCandidate",
    "EngineResult",
    "InteractionOverview",
    "LibraryCandidate",
    "MetricSummary",
    "OfflineRunInput",
    "ProjectAssessment",
    "ProjectDailyReport",
    "ReportItem",
    "SavedBusinessState",
    "SavedLibraryRecord",
    "deduplicate_contents",
    "derive_windows",
    "enforce_analysis_boundaries",
    "normalize_play_count",
    "persona_like_baseline",
    "qianchuan_top_three",
]
